-- Users are the root identity every other table eventually references (directly or via
-- team_members / project_members / tasks.assignee_id / comments.author_id / ...), so this is
-- migration V1.
--
-- gen_random_uuid() is built into PostgreSQL core since v13 (no pgcrypto/uuid-ossp extension
-- needed). UUID primary keys are used throughout this schema rather than serial integers:
-- ids are generated by the database (or could be generated by the application, unlike
-- auto-increment) without coordination, they don't leak "how many rows exist" or insertion
-- order the way a sequential integer does, and they are safe to use as-is in places like
-- Kafka event payloads or URLs without an extra layer of indirection.
CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255) NOT NULL,
    avatar_url      VARCHAR(1024),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Email lookup (login) is the single most frequent query against this table, so it needs an
-- index regardless. It's a UNIQUE index, not just an index, because email uniqueness is a
-- business rule the database must enforce even if application code has a bug.
--
-- It's built on lower(email) rather than on email directly: the application normalizes email
-- to lowercase before every read/write, but a unique index on the raw column would still let
-- "user@example.com" and "User@Example.com" collide as two different rows if that
-- normalization were ever bypassed (a script, a future feature, a bug). Indexing the
-- normalized expression makes the database itself the enforcement point, not just app code.
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));
